<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-088GH95J" failures="1" tests="3" name="Test1" time="9.248" errors="0" timestamp="2022-06-21T21:49:41 EDT">
  <testcase classname="com.RCC.TestData.TC_AlertTest_100" name="checkingAlert" time="3.099"/>
  <testcase classname="com.RCC.TestData.SampleTestCase" name="test1" time="0.012"/>
  <testcase classname="com.RCC.TestData.SampleTestCase" name="test2" time="0.009">
    <failure type="java.lang.AssertionError" message="expected [False] but found [True]">
      <![CDATA[java.lang.AssertionError: expected [False] but found [True]
at com.RCC.TestData.SampleTestCase.test2(SampleTestCase.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- Test1 -->
